=== felixnboi/GroupG-Molekulardynamik/input/XMLFormat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="double_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unsigned_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:unsignedInt"/>
            <xs:element name="y" type="xs:unsignedInt"/>
            <xs:element name="z" type="xs:unsignedInt"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Root element -->
    <xs:element name="simulation">
        <xs:complexType>
        <xs:sequence>

            <!-- Output settings -->
            <xs:element name="outputSettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="baseName" type="xs:string"/>
                        <xs:element name="writeFrequency" type="xs:unsignedInt"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Simulation parameters -->
            <xs:element name="simulationParameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="end_t" type="xs:double"/>
                        <xs:element name="delta_t" type="xs:double"/>
                        <xs:element name="start_t" type="xs:double"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Cuboids -->
            <xs:element name="cuboid" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" type="double_vector"/>
                        <xs:element name="velocity" type="double_vector"/>
                        <xs:element name="dimensions" type="unsigned_vector"/>
                        <xs:element name="distance" type="xs:double"/>
                        <xs:element name="mass" type="xs:double"/>                        
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment3.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <!-- Output settings -->
    <outputSettings>
        <baseName>MD_vtk</baseName>
        <writeFrequency>10</writeFrequency>
    </outputSettings>

    <!-- Simulation parameters -->
    <simulationParameters>
        <end_t>20.0</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
    </simulationParameters>

    <!-- Cuboids -->
    <cuboid>
        <position>
            <x>20.0</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>100</x>
            <y>20</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1</mass>
    </cuboid>

    <cuboid>
        <position>
            <x>70.0</x>
            <y>60.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>20</x>
            <y>20</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1</mass>
    </cuboid>

</simulation>
