=== felixnboi/GroupG-Molekulardynamik/src/io/input/XMLFormat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="double_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unsigned_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:unsignedInt"/>
            <xs:element name="y" type="xs:unsignedInt"/>
            <xs:element name="z" type="xs:unsignedInt"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="boundaryBehavior">
        <xs:restriction base="xs:string">
            <xs:enumeration value="outflow"/>
            <xs:enumeration value="mirror"/>
            <xs:enumeration value="reflecting"/>
            <xs:enumeration value="periodic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="forces">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gravitationalForce"/>
            <xs:enumeration value="lennardJonesForce"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="algorithms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="linkedcell"/>
            <xs:enumeration value="default"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="loglevels">
        <xs:restriction base="xs:string">
            <xs:enumeration value="OFF"/>
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARN"/>
            <xs:enumeration value="INFO"/>
            <xs:enumeration value="DEBUG"/>
            <xs:enumeration value="TRACE"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Root element -->
    <xs:element name="simulation">
        <xs:complexType>
        <xs:sequence>

            <xs:element name="boundaries">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="left" type="boundaryBehavior"/>
                        <xs:element name="right" type="boundaryBehavior"/>
                        <xs:element name="bottom" type="boundaryBehavior"/>
                        <xs:element name="top" type="boundaryBehavior"/>
                        <xs:element name="rear" type="boundaryBehavior"/>
                        <xs:element name="front" type="boundaryBehavior"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Input settings -->
            <xs:element name="inputSettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="inputFile" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Output settings -->
            <xs:element name="outputSettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="baseName" type="xs:string"/>
                        <xs:element name="writeFrequency" type="xs:unsignedInt"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Simulation parameters -->
            <xs:element name="simulationParameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="end_t" type="xs:double"/>
                        <xs:element name="delta_t" type="xs:double"/>
                        <xs:element name="start_t" type="xs:double"/>
                        <xs:element name="force" type="forces"/>                    
                        <xs:element name="algorithm" type="algorithms"/>  
                        <xs:element name="loglevel" type="loglevels"/>  
                        <xs:element name="domain" type="double_vector"/>
                        <xs:element name="domain_start" type="double_vector"/>
                        <xs:element name="cutoff_radius" type="xs:double"/>
                        <xs:element name="grav_constant" type="xs:double"/>                    
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="thermostat" minOccurs="0">
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="T_init" type="xs:double" minOccurs="0"/>        
                        <xs:element name="T_target" type="xs:double" minOccurs="0"/>        
                        <xs:element name="T_diff" type="xs:double" minOccurs="0"/>
                        <xs:element name="n_thermostat" type="xs:unsignedInt"/>
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>                
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Cuboids -->
            <xs:element name="cuboid" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" type="double_vector"/>
                        <xs:element name="velocity" type="double_vector"/>
                        <xs:element name="dimensions" type="unsigned_vector"/>
                        <xs:element name="distance" type="xs:double"/>
                        <xs:element name="mass" type="xs:double"/>    
                        <xs:element name="brownian_motion" type="xs:double"/>
                        <xs:element name="epsilon" type="xs:double"/>
                        <xs:element name="sigma" type="xs:double"/>
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>
                        <xs:element name="type" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            
            <!-- Discs -->
            <xs:element name="disc" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" type="double_vector"/>
                        <xs:element name="velocity" type="double_vector"/>
                        <xs:element name="radius" type="xs:int"/>
                        <xs:element name="distance" type="xs:double"/>
                        <xs:element name="mass" type="xs:double"/>                      
                        <xs:element name="epsilon" type="xs:double"/>                      
                        <xs:element name="sigma" type="xs:double"/>                      
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>
                        <xs:element name="type" type="xs:int"/>               
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== felixnboi/GroupG-Molekulardynamik/input/lc90x90square.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>reflecting</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>MD_vtk</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>0.0005</end_t>
        <delta_t>0.00005</delta_t>
        <start_t>0.0</start_t>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>180.0</x>
            <y>180.0</y>
            <z>1.0</z>
        </domain>
        <cutoff-radius>3.0</cutoff-radius>
    </simulationParameters>

    <cuboid>
        <position>
            <x>20.0</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>90</x>
            <y>90</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <brownian_motion>0.1</brownian_motion>
    </cuboid>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/drop_in_glass.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>reflecting</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>drop_in_glass</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>20.0</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>60.0</x>
            <y>60.0</y>
            <z>1.0</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>3.0</cutoff_radius>
        <grav_constant>0</grav_constant>
    </simulationParameters>

    <cuboid>
        <position>
            <x>18.8775</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>1</x>
            <y>25</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1000000000000000</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
    </cuboid>

    <cuboid>
        <position>
            <x>20</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>21</x>
            <y>1</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1000000000000000</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
    </cuboid>

    <cuboid>
        <position>
            <x>43.5725</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>1</x>
            <y>25</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1000000000000000</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
    </cuboid>

    <disc>
        <position>
            <x>31.225</x>
            <y>50.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <radius>8</radius>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
    </disc>

</simulation>
