=== felixnboi/GroupG-Molekulardynamik/src/io/input/XMLFormat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="double_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unsigned_vector">
        <xs:sequence>
            <xs:element name="x" type="xs:unsignedInt"/>
            <xs:element name="y" type="xs:unsignedInt"/>
            <xs:element name="z" type="xs:unsignedInt"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="boundaryBehavior">
        <xs:restriction base="xs:string">
            <xs:enumeration value="outflow"/>
            <xs:enumeration value="mirror"/>
            <xs:enumeration value="reflecting"/>
            <xs:enumeration value="periodic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="forces">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gravitationalForce"/>
            <xs:enumeration value="lennardJonesForce"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="algorithms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="linkedcell"/>
            <xs:enumeration value="default"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="loglevels">
        <xs:restriction base="xs:string">
            <xs:enumeration value="OFF"/>
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARN"/>
            <xs:enumeration value="INFO"/>
            <xs:enumeration value="DEBUG"/>
            <xs:enumeration value="TRACE"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Root element -->
    <xs:element name="simulation">
        <xs:complexType>
        <xs:sequence>

            <xs:element name="boundaries">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="left" type="boundaryBehavior"/>
                        <xs:element name="right" type="boundaryBehavior"/>
                        <xs:element name="bottom" type="boundaryBehavior"/>
                        <xs:element name="top" type="boundaryBehavior"/>
                        <xs:element name="rear" type="boundaryBehavior"/>
                        <xs:element name="front" type="boundaryBehavior"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Input settings -->
            <xs:element name="inputSettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="inputFile" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Output settings -->
            <xs:element name="outputSettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="baseName" type="xs:string"/>
                        <xs:element name="writeFrequency" type="xs:unsignedInt"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Simulation parameters -->
            <xs:element name="simulationParameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="end_t" type="xs:double"/>
                        <xs:element name="delta_t" type="xs:double"/>
                        <xs:element name="start_t" type="xs:double"/>
                        <xs:element name="force" type="forces"/>                    
                        <xs:element name="algorithm" type="algorithms"/>  
                        <xs:element name="loglevel" type="loglevels"/>  
                        <xs:element name="domain" type="double_vector"/>
                        <xs:element name="domain_start" type="double_vector"/>
                        <xs:element name="cutoff_radius" type="xs:double"/>
                        <xs:element name="grav_constant" type="xs:double"/>                    
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="thermostat" minOccurs="0">
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="T_init" type="xs:double" minOccurs="0"/>        
                        <xs:element name="T_target" type="xs:double" minOccurs="0"/>        
                        <xs:element name="T_diff" type="xs:double" minOccurs="0"/>
                        <xs:element name="n_thermostat" type="xs:unsignedInt"/>
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>                
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <!-- Cuboids -->
            <xs:element name="cuboid" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" type="double_vector"/>
                        <xs:element name="velocity" type="double_vector"/>
                        <xs:element name="dimensions" type="unsigned_vector"/>
                        <xs:element name="distance" type="xs:double"/>
                        <xs:element name="mass" type="xs:double"/>    
                        <xs:element name="brownian_motion" type="xs:double"/>
                        <xs:element name="epsilon" type="xs:double"/>
                        <xs:element name="sigma" type="xs:double"/>
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>
                        <xs:element name="type" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            
            <!-- Discs -->
            <xs:element name="disc" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" type="double_vector"/>
                        <xs:element name="velocity" type="double_vector"/>
                        <xs:element name="radius" type="xs:int"/>
                        <xs:element name="distance" type="xs:double"/>
                        <xs:element name="mass" type="xs:double"/>                      
                        <xs:element name="epsilon" type="xs:double"/>                      
                        <xs:element name="sigma" type="xs:double"/>                      
                        <xs:element name="brownian_motion_dimension" type="xs:unsignedInt"/>
                        <xs:element name="type" type="xs:int"/>               
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment5_task4.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>outflow</left>
        <right>outflow</right>
        <bottom>periodic</bottom>
        <top>periodic</top>
        <rear>periodic</rear>
        <front>periodic</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>ass5_task4</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>500</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>30.0</x>
            <y>30.0</y>
            <z>12.0</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>2.5</cutoff_radius>
        <grav_constant>-0.8</grav_constant>
        <walls_flag>true</walls_flag>
    </simulationParameters>

    <thermostat>
        <T_init>40</T_init>
        <n_thermostat>10</n_thermostat>
        <brownian_motion_dimension>3</brownian_motion_dimension>
    </thermostat>

     <cuboid>
        <position>
            <x>1.0</x>
            <y>0.5</y>
            <z>0.5</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>2</x>
            <y>30</y>
            <z>12</z>
        </dimensions>
        <distance>1.0</distance>
        <mass>1.0</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>2.0</epsilon>
        <sigma>1.1</sigma>
        <brownian_motion_dimension>3</brownian_motion_dimension>
        <type>0</type>
        <is_outer>true</is_outer>
    </cuboid>


     <cuboid>
        <position>
            <x>27.2</x>
            <y>0.5</y>
            <z>0.5</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>2</x>
            <y>30</y>
            <z>12</z>
        </dimensions>
        <distance>1.0</distance>
        <mass>1.0</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>2.0</epsilon>
        <sigma>1.1</sigma>
        <brownian_motion_dimension>3</brownian_motion_dimension>
        <type>1</type>
        <is_outer>true</is_outer>
    </cuboid>

    
     <cuboid>
        <position>
            <x>3.2</x>
            <y>0.6</y>
            <z>0.6</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>20</x>
            <y>25</y>
            <z>10</z>
        </dimensions>
        <distance>1.2</distance>
        <mass>1.0</mass>
        <brownian_motion>0.0</brownian_motion>
        <epsilon>1.0</epsilon>
        <sigma>1.0</sigma>
        <brownian_motion_dimension>3</brownian_motion_dimension>
        <type>2</type>
        <is_outer>false</is_outer>
    </cuboid>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment3_task4.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>reflecting</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>ass3_task4</baseName>
        <writeFrequency>200</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>10.0</end_t>
        <delta_t>0.00005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>120.0</x>
            <y>50.0</y>
            <z>1.0</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>3.0</cutoff_radius>
        <grav_constant>0</grav_constant>
    </simulationParameters>

    <disc>
        <position>
            <x>60.0</x>
            <y>25.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <radius>15</radius>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
        <type>1</type>
    </disc>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment3_task2.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>reflecting</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>ass3_task2</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>20.0</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>180.0</x>
            <y>90.0</y>
            <z>1.0</z>
        </domain>
        <cutoff-radius>3.0</cutoff-radius>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>3.0</cutoff_radius>
        <grav_constant>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </grav_constant>
        <walls_flag>false</walls_flag>
    </simulationParameters>

    <cuboid>
        <position>
            <x>20.0</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>100</x>
            <y>20</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <brownian_motion>0.1</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
        <type>0</type> 
        <is_outer>false</is_outer>
    </cuboid>

    <cuboid>
        <position>
            <x>70.0</x>
            <y>60.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>20</x>
            <y>20</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <brownian_motion>0.1</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
        <type>1</type>
        <is_outer>false</is_outer>
    </cuboid>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>outflow</left>
        <right>mirror</right>
        <bottom>reflecting</bottom>
        <top>outflow</top>
        <rear>mirror</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>test1</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>test2</baseName>
        <writeFrequency>1</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>2</end_t>
        <delta_t>3</delta_t>
        <start_t>4</start_t>
        <epsilon>5</epsilon>
        <sigma>6</sigma>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>8</x>
            <y>9</y>
            <z>10</z>
        </domain>
        <cutoff-radius>11</cutoff-radius>
    </simulationParameters>

    <cuboid>
        <position>
            <x>12</x>
            <y>13</y>
            <z>14</z>
        </position>
        <velocity>
            <x>15</x>
            <y>16</y>
            <z>17</z>
        </velocity>
        <dimensions>
            <x>18</x>
            <y>19</y>
            <z>20</z>
        </dimensions>
        <distance>21</distance>
        <mass>22</mass>
        <brownian_motion>7</brownian_motion>
    </cuboid>

    <disc>
        <position>
            <x>23</x>
            <y>24</y>
            <z>25</z>
        </position>
        <velocity>
            <x>26</x>
            <y>27</y>
            <z>28</z>
        </velocity>
        <radius>29</radius>
        <distance>30</distance>
        <mass>31</mass>
    </disc>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/src/io/input/Assignment2.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <!-- Output settings -->
    <outputSettings>
        <baseName>MD_vtk</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <!-- Simulation parameters -->
    <simulationParameters>
        <end_t>5.0</end_t>
        <delta_t>0.0002</delta_t>
        <start_t>0.0</start_t>
    </simulationParameters>

    <!-- Cuboids -->
    <cuboid>
        <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>40</x>
            <y>8</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1</mass>
    </cuboid>

    <cuboid>
        <position>
            <x>15.0</x>
            <y>15.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>8</x>
            <y>8</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1</mass>
    </cuboid>

    <!-- Add more cuboids if necessary -->

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/default90x90square.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>reflecting</rear>
        <front>reflecting</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>MD_vtk</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>0.005</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>default</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>180.0</x>
            <y>90.0</y>
            <z>1.0</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>3.0</cutoff_radius>
        <grav_constant>0</grav_constant>
        <walls_flag>false</walls_flag>
    </simulationParameters>

    <cuboid>
        <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>90</x>
            <y>90</y>
            <z>1</z>
        </dimensions>
        <distance>1.1225</distance>
        <mass>1.0</mass>
        <brownian_motion>0.1</brownian_motion>
        <epsilon>5.0</epsilon>
        <sigma>1.0</sigma>
        <brownian_motion_dimension>2</brownian_motion_dimension>
        <type>0</type>
        <is_outer>false</is_outer>
    </cuboid>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment4_task2_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>periodic</left>
        <right>periodic</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>outflow</rear>
        <front>outflow</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>ass4_task2_1</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>25</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>63.0</x>
            <y>36.0</y>
            <z>1</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>2.5</cutoff_radius>
        <grav_constant>
            <x>0.0</x>
            <y>-12.44</y>
            <z>0.0</z>
        </grav_constant>
        <walls_flag>false</walls_flag>
    </simulationParameters>

    <thermostat>
        <T_init>40</T_init>
        <n_thermostat>1000</n_thermostat>
        <brownian_motion_dimension>2</brownian_motion_dimension>
    </thermostat>

    <openmp>
        <num_threads>4</num_threads>
        <parallelizationstrategy>second</parallelizationstrategy>
    </openmp>

    <cuboid>
        <position>
            <x>0.6</x>
            <y>2.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>50</x>
            <y>14</y>
            <z>1</z>
        </dimensions>
        <distance>1.2</distance>
        <mass>1.0</mass>
        <brownian_motion>0.1</brownian_motion>
        <epsilon>1.0</epsilon>
        <sigma>1.0</sigma>
        <brownian_motion_dimension>2</brownian_motion_dimension>
        <type>1</type> 
        <is_outer>false</is_outer>
    </cuboid>

    <cuboid>
        <position>
            <x>0.6</x>
            <y>19.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <dimensions>
            <x>50</x>
            <y>14</y>
            <z>1</z>
        </dimensions>
        <distance>1.2</distance>
        <mass>2.0</mass>
        <brownian_motion>0.1</brownian_motion>
        <epsilon>1.0</epsilon>
        <sigma>0.9412</sigma>
        <brownian_motion_dimension>2</brownian_motion_dimension>
        <type>2</type> 
        <is_outer>false</is_outer>
    </cuboid>

</simulation>

=== felixnboi/GroupG-Molekulardynamik/input/Assignment4_task3_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/io/input/XMLFormat.xsd">

    <boundaries>
        <left>reflecting</left>
        <right>reflecting</right>
        <bottom>reflecting</bottom>
        <top>reflecting</top>
        <rear>outflow</rear>
        <front>outflow</front>
    </boundaries>

    <inputSettings>
        <inputFile>../input/generated-input.txt</inputFile>
    </inputSettings>

    <outputSettings>
        <baseName>ass4_task3_2</baseName>
        <writeFrequency>100</writeFrequency>
    </outputSettings>

    <simulationParameters>
        <end_t>40</end_t>
        <delta_t>0.0005</delta_t>
        <start_t>0.0</start_t>
        <force>lennardJonesForce</force>
        <algorithm>linkedcell</algorithm>
        <loglevel>INFO</loglevel>
        <domain>
            <x>303.0</x>
            <y>180.0</y>
            <z>1</z>
        </domain>
        <domain_start>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </domain_start>
        <cutoff_radius>3</cutoff_radius>
        <grav_constant>-12.44</grav_constant>
        <walls_flag>false</walls_flag>
    </simulationParameters>

    <checkpoint>
        <merge_file>../input/checkpoint.txt</merge_file>
    </checkpoint>

    <disc>
        <position>
            <x>150.0</x>
            <y>150.0</y>
            <z>0.0</z>
        </position>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <radius>20</radius>
        <distance>1.2</distance>
        <mass>1.0</mass>
        <epsilon>1.0</epsilon>
        <sigma>1.2</sigma>
        <brownian_motion_dimension>2</brownian_motion_dimension>
        <type>1</type>
        <is_outer>false</is_outer>
    </disc>

</simulation>
